steps:
  # Build the container image

  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '--tag',
        'gcr.io/inductive-gift-351105/sou-web-net:$COMMIT_SHA',
        '--build-arg',
        '_CONTENTFUL_SPACE_ID=$_CONTENTFUL_SPACE_ID',
        '--build-arg',
        '_CONTENTFUL_DELIVERY_TOKEN=$_CONTENTFUL_DELIVERY_TOKEN',
        '--build-arg',
        '_NEXT_PUBLIC_GA_ID=$_NEXT_PUBLIC_GA_ID',
        '--build-arg',
        '_MAIL_USER=$_MAIL_USER',
        '--build-arg',
        '_MAIL_PASS=$_MAIL_PASS',
        '--build-arg',
        '_MAIL_TO=$_MAIL_TO',
        '.',
      ]
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/inductive-gift-351105/sou-web-net:$COMMIT_SHA']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run',
        'deploy',
        'sou-web-net',
        '--image',
        'gcr.io/inductive-gift-351105/sou-web-net:$COMMIT_SHA',
        '--region',
        'asia-northeast1',
        '--platform',
        'managed',
      ]
images:
  - 'gcr.io/inductive-gift-351105/sou-web-net'
