steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/inductive-gift-351105/sou-web-net',
    "--build-arg", "_CONTENTFUL_SPACE_ID=$_CONTENTFUL_SPACE_ID", "_CONTENTFUL_DELIVERY_TOKEN=$_CONTENTFUL_DELIVERY_TOKEN",
    "_NEXT_PUBLIC_GA_ID=$_NEXT_PUBLIC_GA_ID", "_MAIL_USER=$_MAIL_USER", "_MAIL_PASS=$_MAIL_PASS", "_MAIL_TO=$_MAIL_TO", '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/inductive-gift-351105/sou-web-net']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'sou-web-net'
      - '--image'
      - 'gcr.io/inductive-gift-351105/sou-web-net'
      - '--region'
      - 'asia-northeast1'
      - '--platform'
      - 'managed'
images:
  - 'gcr.io/inductive-gift-351105/sou-web-net'
