steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '--build-arg',
        '_CONTENTFUL_SPACE_ID=$_CONTENTFUL_SPACE_ID',
        '--build-arg',
        '_CONTENTFUL_DELIVERY_TOKEN=$_CONTENTFUL_DELIVERY_TOKEN',
        '--build-arg',
        '_NEXT_PUBLIC_GA_ID=$_NEXT_PUBLIC_GA_ID',
        '--build-arg',
        '_MAIL_USER=$_MAIL_USER',
        '--build-arg',
        '_MAIL_PASS=$_MAIL_PASS',
        '--build-arg',
        '_MAIL_TO=$_MAIL_TO',
        '-t',
        '$_GCR_HOSTNAME/$PROJECT_ID/$_SERVICE_NAME',
        '.',
      ]
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '$_GCR_HOSTNAME/$PROJECT_ID/$_SERVICE_NAME']
  # Deploy container image to Cloud Run
  - name: '$_GCR_HOSTNAME/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run',
        'deploy',
        '$_SERVICE_NAME',
        '--image',
        '$_GCR_HOSTNAME/$PROJECT_ID/$_SERVICE_NAME',
        '--region',
        '$_DEPLOY_REGION',
        '--platform',
        '$_PLATFORM',
      ]
images:
  - '$_GCR_HOSTNAME/$PROJECT_ID/$_SERVICE_NAME'
