steps:
  - name: 'gcr.io/inductive-gift-351105/sou-web-net'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/inductive-gift-351105:$COMMIT_SHA', '.']
    timeout: 1200s
  - name: 'gcr.io/inductive-gift-351105/sou-web-net'
    args: ['push', 'gcr.io/$PROJECT_ID/inductive-gift-351105:$COMMIT_SHA']
    timeout: 1200s
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'API-Server'
      - '--image'
      - 'gcr.io/$PROJECT_ID/inductive-gift-351105:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
images:
  - 'gcr.io/$PROJECT_ID/inductive-gift-351105:$COMMIT_SHA'
