steps:
  # Build the container image

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - -c
      - >-
        docker build
        --file=Dockerfile
        --build-arg=_CONTENTFUL_SPACE_ID=$_CONTENTFUL_SPACE_ID
        --build-arg=_CONTENTFUL_DELIVERY_TOKEN=$_CONTENTFUL_DELIVERY_TOKEN
        --build-arg=_NEXT_PUBLIC_GA_ID=$_NEXT_PUBLIC_GA_ID
        --build-arg=_MAIL_USER=$_MAIL_USER
        --build-arg=_MAIL_PASS=$_MAIL_PASS
        --build-arg=_MAIL_TO=$_MAIL_TO
        --tag=gcr.io/inductive-gift-351105/sou-web-net
        .
    env:
      - '_NEXT_PUBLIC_CONTENTFUL_SPACE_ID=$_CONTENTFUL_SPACE_ID'
      - '_NEXT_PUBLIC_CONTENTFUL_DELIVERY_TOKEN=$_CONTENTFUL_DELIVERY_TOKEN'
      - '_NEXT_PUBLIC_GA_ID=$_NEXT_PUBLIC_GA_ID'
      - '_NEXT_PUBLIC_MAIL_USER=$_MAIL_USER'
      - '_NEXT_PUBLIC_MAIL_PASS=$_MAIL_PASS'
      - '_NEXT_PUBLIC_MAIL_TO=$_MAIL_TO'
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/inductive-gift-351105/sou-web-net']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run',
        'deploy',
        'sou-web-net',
        '--image',
        'gcr.io/inductive-gift-351105/sou-web-net',
        '--region',
        'asia-northeast1',
        '--platform',
        'managed',
        '--allow-unauthenticated',
        '--update-env-vars',
        'NODE_ENV=production',
        'NEXT_CONTENTFUL_SPACE_ID=${_CONTENTFUL_SPACE_ID}',
        'NODE_ENV=production',
        'NEXT_CONTENTFUL_DELIVERY_TOKEN=${_CONTENTFUL_DELIVERY_TOKEN}',
        'NODE_ENV=production',
        'NEXT_PUBLIC_GA_ID=${_NEXT_PUBLIC_GA_ID}',
        'NODE_ENV=production',
        'NEXT_MAIL_USER=${_MAIL_USER}',
        'NODE_ENV=production',
        'NEXT_MAIL_PASS=${_MAIL_PASS,NEXT_MAIL_TO=$_MAIL_TO}',
      ]
images:
  - 'gcr.io/inductive-gift-351105/sou-web-net'
options:
  substitution_option: 'ALLOW_LOOSE'
substitutions:
  _CONTENTFUL_SPACE_ID: '$_CONTENTFUL_SPACE_ID'
  _CONTENTFUL_DELIVERY_TOKEN: '$_CONTENTFUL_DELIVERY_TOKEN'
  _NEXT_PUBLIC_GA_ID: '$_NEXT_PUBLIC_GA_ID'
  _MAIL_USER: '$_MAIL_USER'
  _MAIL_PASS: '$_MAIL_PASS'
  _MAIL_TO: '$_MAIL_TO'
